version: '3.7'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: order-file-converter

  redis:
    image: redis:latest
    ports:
      - "6379:6379"